[tool.pytest.ini_options]
addopts = "-ra"
testpaths = [
    "apps/coordinator-api/tests",
    "apps/miner-node/tests"
]
asyncio_default_fixture_loop_scope = "function"
pythonpath = [
    "packages/py/aitbc-core/src",
    "packages/py/aitbc-crypto/src",
    "packages/py/aitbc-p2p/src",
    "packages/py/aitbc-sdk/src"
]
